# Site settings
title: H3xL00m's Personal Site
name: H3xL00m's Personal Site
url: "https://h3xl00m.github.io"
email: h3xl00m@gmail.com
description: H3xL00m's Personal Site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: h3xl00m  # Twitter ID
github_username:  h3xl00m # Github ID
LinkedIn_username: h3xl00m # LinkedIn ID
google-analytics_id: h3xl00m  # Google Analytics ID
rss_url: "/feed.xml"  # RSS 订阅 URL
logo_image: "/images/logo.png"  # LOGO 图片地址
# Build settings
gems: [jekyll-paginate]
markdown: rdiscount
highlighter: pygments
permalink: /:title/
paginate: 8
paginate_path: page/:num
 